Awesome Events (Back-End) [Final Capstone Project]
aristides1000/awesome-events-back-end pull request #66
Opened 2021-11-24 18:39 UTC by aristides1000

## In this PR we accomplished the following activities:

## Preliminary Phase

- [x] Select a theme for your website.
- [x] Build an Entity Relationship Diagram (ERD).
- [x] Define the database schema on the back-end side.

## Back-end Phase

- [x] Create a repo on GitHub
- [x] Generate a model for Item (with details)
- [x] Modify controllers and routes to handle “Reserve Item/Appointment” as a POST Request.
- [x] Resolve conflicts.
- [x] Unify all features.
- [x] Set-up linters check
- [x] Set up routes, namespaces, and basic controllers
- [x] Modify controllers and routes to handle “Delete Item” as a DELETE Request.
- [x] Resolve conflicts.
- [x] Unify all features.
- [x] Setting up the login procedure for the user, without proper authentication.
- [x] Modify controllers and routes to handle “Add Item” as a POST Request.
- [x] Modify controllers and routes to handle “My Reservations” as a GET Request.
- [x] Resolve conflicts.
- [x] Unify all features.

## Front-End

- [x] Set-up linters check.
- [x] Create a Navbar component with a list of links 
- [x] Create a “New Item Form” that will be accessed from the “Add item" link in the navigation panel.
- [x] Create a component to show a list of the user’s reservations (with information about item name, date, and city).
- [x] This component should be accessed from the "My reservations" link in the navigation panel they can see.
- [x] Add styles to the Navbar component.
- [x] Add styles to the “New Item Form” component.
- [x] Add styles to show users' reservations list.
- [x] Resolve conflicts.
- [x] Unify all features.
- [x] Curate images, fonts, colors
- [x] Create a Navigation Panel component, with the following Links:
- [x] Motorcycles/doctors/classes/items that you selected as a theme
- "Reserve" form.
- "My reservations".
- [x] Create a component for the user to select a specific item.
- [x] They can see the details page with its full description (skip the "Rotate image" button).
- [x] Create a component to list all the items with their respective title (“items list”).
- [x] This component should be accessed from the "Delete item" link in the navigation panel.
- [x] Add a “Delete Button” to each item in the “items list” component.
- [x] When the user clicks the "Delete Button”, the selected item is marked as removed and does not show on the main list anymore.
- [x] Add styles to the component created for the user to select a specific item.
- [x] Add styles to the “items list” component.
- [x] Resolve conflicts.
- [x] Unify all features.
- [x] Create a repo on GitHub
- [x] Setting up the login procedure for the user, without proper authentication.
- [x] Create a Details Page where the user can click the "Reserve" button.
- [x] Create a component to reserve an appointment, the user has to select a date and city (username and selected item are auto-filled).
- [x] Use the design based on the "Book a vespa test-ride" and add all necessary inputs.
- [x] The user can also access the "Reserve" page from the navigation panel. In that case, only the username is auto-filled.
- [x] Add styles to the navigation panel component.
- [x] Add styles to the details page.
- [x] Add styles to the component created to reserve appointments.
- [x] Resolve conflicts.
- [x] Unify all features.

## General Tasks and Final Touches

- [x] Add full documentation for your API, update README on the back-end repository, and create a Pull Request.
- [x] Update README on the front-end repository, and create a Pull Request.

Participants:
- @aristides1000
- @DanSam5K 
- @enionsouza 

Find also attached is the [Pull Request](https://github.com/enionsouza/awesome-events-front-end/pull/21
) in the front-end side.

2021-11-24 20:26 UTC, MuriloRoque requested changes
```markdown
Hi @aristides1000, @DanSam5K and @enionsouza, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

```

2021-11-24 20:26 UTC, MuriloRoque commented on config/routes.rb
> +  resources :events
- [x] These two lines are defining all of the common routes for these models, I think you should delete them since it will create undesired routes in your app. For example, what happens if I access `/attendances/1` with a `GET` request? I will definitely get a Rails error since the route is defined but it leads to no actions.

2021-11-24 20:26 UTC, MuriloRoque commented on app/controllers/attendances_controller.rb
> +      end
**[OPTIONAL]** I'm sure you have heard about "Smart Models, Thin Controllers, and Dumb Views" while studying Rails. This is totally optional, but you could take all of this logic out of the controller and create methods inside of the models, calling them here and improving your code. Also, don't forget we can always use _scopes_ for some of the operations.

2021-11-24 20:26 UTC, MuriloRoque commented on test/controllers/attendances_controller_test.rb
> +end
- [x] Please write some tests here.

2021-11-24 20:26 UTC, MuriloRoque commented on test/controllers/events_controller_test.rb
> +end
- [x] Please write some tests here.

2021-11-24 20:26 UTC, MuriloRoque commented on test/models/attendance_test.rb
> +end
- [x] Please write some tests here.

2021-11-24 20:26 UTC, MuriloRoque commented on test/models/event_test.rb
> +end
- [x] Please write some tests here.

2021-11-24 20:26 UTC, MuriloRoque commented on test/models/user_test.rb
> +end
- [x] Please write some tests here.

2021-11-25 19:24 UTC, MuriloRoque approved these changes
Hi @aristides1000, @DanSam5K, @enionsouza, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-11-25 19:28 UTC, merged

2021-11-25 20:05 UTC, DanSam5K commented
- Thank you @MuriloRoque 🤝